### ISSUE TITLE
how can i do user add or change root password

### ISSUE THREAD

**Issue by mgcnrx11** [phusion/baseimage-docker#111]
On baseimage, every time i use the passwd or adduser cmmand. I got this error message:
2014 Jul 17 02:32:20 1d45af1ed43f PAM audit_log_acct_message() failed: Operation not permitted
passwd: System error
passwd: password unchanged

I do that in ssh session. IS that anything I shuold modify in sshd_config?

**Comment by FooBarWidget** [comment]
I think this issue is related to:

 * https://github.com/phusion/baseimage-docker/issues/181
 * https://github.com/docker/docker/issues/6345

The `passwd` tool no longer triggers the bug, but pbuilder still does. The instructions in https://github.com/phusion/baseimage-docker/issues/181 fixed it for me.
