### ISSUE TITLE
syslog-ng leaves its sockets everywhere and never cleans them up

### ISSUE THREAD

**Issue by kingdonb** [phusion/baseimage-docker#128]
#25 #31 #59 #60 (fixed in #71) is back

In another slightly different form:

Aug  7 15:03:22 sshbox syslog-ng[16]: Error opening control socket, bind() failed; socket='/var/lib/syslog-ng/syslog-ng.ctl', error='Address already in use (98)'

I get this error from syslog after committing a baseimage container and running the new image.

Look in /var/lib/syslog-ng and sure enough, there's an empty file syslog-ng.ctl with 755 mode.

The fix is probably the same as #25 but for `/var/lib/syslog-ng/syslog-ng.ctl`
(if it's not testing positive as `-S`, it should be `rm`'ed.)

**Comment by AKIvan** [comment]
@kingdonb can you tell me the fix for this as im little confused. I have used syslog-ng with TLS and MySQL and works ok till i have to decide to change the DB and updated from 3.5 to syslog-ng 3.8. So when i do this i have error saying that 

> Error binding socket; addr='AF_INET(0.0.0.0:6514)', error='Address already in use (98)'
> [2016-04-22T12:46:33.433483] Error initializing message pipeline;

in the syslog-ng.ctl there is nothing and im using CentOS 7.
