### ISSUE TITLE
explain why runit

### ISSUE THREAD

**Issue by tcurdt** [phusion/baseimage-docker#164]
AFAIU docker now supports auto restart of containers - if there is a reason to still use runit it would be great to explain this in the docs.

**Comment by endersonmaia** [comment]
See the `runit` table row here : https://github.com/phusion/baseimage-docker/blob/master/README.md#whats_inside_overview

Here too: http://phusion.github.io/baseimage-docker/ in the `runit` section.

I think it's enough explanation, and this issue could be closed.

**Comment by tcurdt** [comment]
I would say: Because the baseimage allows running multiple services the docker auto restart policy cannot be used as it will only restart on the main process crashing. As a result there needs to be a service manager and `runit` is much easier to use and more lightway than e.g. upstart.

**Comment by FooBarWidget** [comment]
See also the reasons I listed at http://blog.phusion.nl/2015/01/20/baseimage-docker-fat-containers-treating-containers-vms/, section "Why multiple processes?"

**Comment by tcurdt** [comment]
@FooBarWidget I guess you refer to the reaping problem? http://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

Is there a `docker` issue open for that? Would be nice to link it here.

**Comment by FooBarWidget** [comment]
Runit is not there to solve the reaping problem. Rather, it's to support multiple processes. Multiple processes are encouraged for security (through process and user isolation). Runit uses less memory than Supervisord because Runit is written in C and Supervisord in Python. And in some use cases, process restarts in the container are preferable over whole-container restarts.

I'm not aware of of a Docker issue tracker entry for the PID 1 problem.

**Comment by tcurdt** [comment]
@FooBarWidget ...but `runit` (besides supporting multiple process) should also solve the reaping problem IIUC?

**Comment by FooBarWidget** [comment]
No it doesn't. That's why my_init is PID 1, not Runit.

**Comment by tcurdt** [comment]
Ah I see. So essentially one could just use something like https://github.com/phusion/baseimage-docker/blob/rel-0.9.16/image/bin/my_init and use that in a single service container, too.

@FooBarWidget Then I don't get what other reason for `runit` you meant. The separate users?

**Comment by FooBarWidget** [comment]
That's right, you can use my_init and use it in a single service container.

In baseimage-docker, we encourage running multiple processes in a single container. Not necessarily multiple *services* though. A logical service can consist of multiple OS processes, and we provide the facilities to easily do that.

For example, in a container for a Node.js web application, you can run the Phusion Passenger application server as well as the Nginx web server. For security reasons, you can make Node.js, Phusion Passenger and Nginx all run as different users inside the same container, so that a security vulnerability in one component doesn't affect the other components as easily.

**Comment by endersonmaia** [comment]
`runit` site says it can be PID 1.

> The program runit is intended to run as Unix process no 1, it is automatically started by the runit-init /sbin/init-replacement if this is started by the kernel.
> source : http://smarden.org/runit/

@FooBarWidget is there any relevant problem that made you build `my_init` for it ?

This issue's question is "why runit" and now I ask "why my_init".

**Comment by d-snp** [comment]
The runit site is a bit confusing, but it's not actually runit that's the init process, it's runit-init process. My guess as to why @FooBarWidget isn't using runit-init is probably because runit-init does more than just reaping processes, and that's not desirable in a Docker container. my_init just does reaping.

**Comment by FooBarWidget** [comment]
I tried runit-init before writing my_init, but ultimately it didn't work out. Runit-init doesn't handle SIGTERM properly, doesn't properly shutdown all the other processes in the container, has no facilities for running custom boot time scripts, etc.

**Comment by ebuildy** [comment]
I am using nginx with Docker-gen to make a kind of dynamic configuration, how can I reload/restart Nginx? I know supervisor has the ````supervisord restart nginx```` syntax but didn't find how to do this with phusion image.

Thanks,

**Comment by FooBarWidget** [comment]
sv restart /etc/service/nginx. Read the Runit docs for more information.
