### ISSUE TITLE
Skipping envs

### ISSUE THREAD

**Issue by mirek** [phusion/baseimage-docker#183]
Great stuff, thanks. Is there a reason you're skipping some environment variables in directory export and shell file export and not json https://github.com/phusion/baseimage-docker/blob/master/image/bin/my_init#L75-L87 ?

**Comment by FooBarWidget** [comment]
The shell export file works by directly setting environment variables inside the shell. But HOME, USER, GROUP etc are special environment variables that are used by the shell, or by programs typically invoked from the shell. They're user-specific environment variables that are set by PAM, sudo, etc. As such, we needs to make sure we're not overriding them.

We do not exclude these environment variables from the JSON export because we can assume that programs that load the JSON do not blindly set them as environment variables, as the shell does.
