### ISSUE TITLE
Unset environment variable (access ENTRYPOINT process)

### ISSUE THREAD

**Issue by Toilal** [phusion/baseimage-docker#201]
I'm using docker `run -e PASSWORD=<password>` to give a default password for a dockerized service, and for security reasons I would like to unset this password after `my_init` scripts are executed.

Problem is that I can't find any entrypoint using baseimage-docker to unset this variable from root process environment. Calling `unset PASSWORD` in a script located in `/etc/my_init.d` has no effect, because scripts from this directory are forked and can't change the parent process environment.

Is it possible to source a script in root process environment ? (ENTRYPOINT process)

Maybe new scripts could be executed if exists (`my_init_before` and `my_init_after`), that would be sourced from the main entrypoint script ...

**Comment by FooBarWidget** [comment]
`unset` and `export` don't work, because that's how environment variables are. They only affect the current process and child processes, not anything else. That's why my_init provides a special way to set environment variables in other processes, in the form of the /etc/container_environment directory.

Unsetting an environment variable just involves deleting /etc/container_environment/PASSWORD in an init script.

**Comment by Toilal** [comment]
Thanks for explanations. 

I understand how the `/etc/container_environment` directory may solve issues related to environment variable, but it doesn't really solve this one. But maybe it's a Docker issue, feel free to close if it's out of scope ...

```
toilal@box:~$ docker run -it --rm --name test -e PASSWORD=secret phusion/baseimage
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 8
Mar 10 09:14:09 c338538fe4cf syslog-ng[15]: syslog-ng starting up; version='3.5.3'
```

```
toilal@box:~$ docker exec -it test bash
root@f6e88f853697:/# rm /etc/container_environment/*
root@f6e88f853697:/# exit
exit
toilal@box:~$ docker exec -it test bash
root@f6e88f853697:/# env | grep PASSWORD
PASSWORD=secret
root@f6e88f853697:/# 
```

**Comment by FooBarWidget** [comment]
It doesn't work if you do it from a bash session. You have to delete it from a startup script. That's because it's implemented as follows:

1. my_init dumps all environment variables to /etc/container_environment.
2. my_init runs all scripts in /etc/init.d.
3. my_init clears its own environment variables, then imports them from /etc/container_environment.
4. my_init runs the final command.

Any environment variable modifications you want to make *have* to be done in step 2. When you do it in a bash session, you are doing it well beyond step 4.

**Comment by Toilal** [comment]
I see ! I'll give it a try, thanks a lot.

**Comment by Toilal** [comment]
It still doesn't work. Even if environment variable is removed in a startup script (/etc/init.d) using `rm /etc/container_environment/PASSWORD`, it still appear in a bash `env` command.

I think it would work if I set environment variable in another `/etc/init.d` script, but I want the environment variable to be provided by user when running the container with `-e` flag.

But i really think my problem would occur with any baseimage, so it's more a Docker issue, i'll close now ...
