### ISSUE TITLE
Runit repeats the start operation

### ISSUE THREAD

**Issue by rajitha-wijayaratne** [phusion/baseimage-docker#207]
Hello,

I have a runit starting PHP-FPM process as follows.

```
#!/bin/sh
prefix=/opt/php
exec_prefix=${prefix}
php_fpm_BIN=${exec_prefix}/sbin/php-fpm
php_fpm_CONF=${prefix}/etc/php-fpm.conf
php_opts="--fpm-config $php_fpm_CONF"

exec $php_fpm_BIN --daemonize $php_opts
```

It runs OK and the process is started.  However, runit appears to keep starting the same process again in an endless loop.  The second and subsequent times it fails because the port is now in use.  The following message keeps repeating in the php-fpm log file.

```
[21-Mar-2015 04:02:23] ERROR: FPM initialization failed
[21-Mar-2015 04:02:24] ERROR: unable to bind listening socket for address '127.0.0.1:9000': Address already in
```

How can I solve this? Thanks.

**Comment by kingdonb** [comment]
The problem is almost certainly `--daemonize`.  I don't know anything about PHP-FPM, but if that means the same thing it means in any other service it's launching your service using a model of "fork and exec"

You need to adapt your services so they don't return; runit assumes that any return from the service is a failure and starts the service again.  Remove `--daemonize` and the service will not background, you will get only one instance and runit will only start it again if it crashes and returns control.

**Comment by linusyong** [comment]
I have done this before with HA Proxy + Nginx + PHP-FPM, what kingdonb said is right that you shouldn't daemonize it.

Hope the files I publish here might be of help:
https://github.com/linusyong/docker/tree/master/nginx-php-fpm

**Comment by rajitha-wijayaratne** [comment]
Thanks for your help.  Removing --daemonize stops the problem.
