### ISSUE TITLE
invoke-rc.d <service> stop fails

### ISSUE THREAD

**Issue by osr-admin** [phusion/baseimage-docker#216]
Some ubuntu packages (such as nginx and cups) include a logrotate configuration file in /etc/logrotate.d. In order to rotate logs, i.e. to change the file a daemon writes to, it is restarted, in this case by invoke-rc.d --quiet <service> stops. In Phusion-base, this fails (if one omits --quiet, then invoke-rc.d responds with "policy-rc.d denied execution of stop").

Unfortunately this leaves us with the situation that logrotate is unable to restart a service, and although the log files are still rotated, the daemon writes future logs into /dev/null.

Phusion-base users, if aware of the issue, could modify every daemon's logrotate configuration file to invoke runit instead of invoke-rc.d, but perhaps something could be done in phusion-base instead?

**Comment by mkiesel** [comment]
There are other occasions that depend on `invoke-rc.d` as well, such as `apt-get upgrade` - which might even hang as it is now, as for example a mysql upgrade will wait for mysql to stop/restart before running table upgrades.

runit provides some LSB init scripts compliance, see http://smarden.org/runit/faq.html#lsb . This should probably get mentioned in the baseimage docs in the "Adding additional daemons" section, probably along with `dpkg-divert` (I guess divert would be the proper way to make sure the links to `sv` don't get overwritten on upgrades - not sure about that).

**Comment by hyperknot** [comment]
Two points: most importantly you are not supposed to upgrade a system inside a Docker image, except at build time. The whole point of Docker is to make sure that you are on a clean, up-from-the-ground image and not something which has been tinkered with by unreliable upgrade scripts.

So never `apt-get upgrade mysql`, just `apt-get install` and if you want to upgrade then run a build without cache.

Adding a section to docs might be useful though as it might help someone.

**Comment by kingdonb** [comment]
@hyperknot While this is maybe a best practice and more idiomatic than upgrading in-place, it sounds very complicated given the fact that tables also may need to be upgraded.

You can put the table data in a volume, then attach the volume to your new container and perform table upgrades manually, but you don't have to.  There is also no reason you must do it this way if you choose to use a volume (which is definitely a recommended best practice for something like MySQL server.)

But even with a volume, you could upgrade in-place, let the package manager handle the table upgrades for you, and use `docker commit` to build a new image once the upgrades are done.  If you are worried about running afoul of the image layer limit, or eventually your image size ballooning out of control, you can also export and flatten your image (as in:

`docker export mycontainer | docker import - mynewimage:imported`

None of this actually comes close to solving the policy-rc.d issue raised here, though.

**Comment by hyperknot** [comment]
@kingdonb that is a very specific issue of upgrading MySQL. I would be very surprised if the recommended way would be to apt-get upgrade mysql which would somehow automagically upgrade all tables.

Usually DBs have a very detailed manual about how to upgrade dbs. While the db size is reasonable the simplest method is simply to do an sql dump from the old version and import it into the new version. Docker is perfect for this as you can just start a different image for each version.

About logrotate, why not just use the copy method which doesn't require restarting at all? They say there is like a millisecond time when something might not be logged but it doesn't sound like a big problem to me.

**Comment by rdxmb** [comment]
> I do think the right way will involve apt-get upgrade

This is not recommended from Docker:
> You should avoid RUN apt-get upgrade or dist-upgrade
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

**Comment by kingdonb** [comment]
> You should avoid RUN apt-get upgrade or dist-upgrade, as many of the “essential” packages from the parent images won’t upgrade inside an unprivileged container. If a package contained in the parent image is out-of-date, you should contact its maintainers. If you know there’s a particular package, foo, that needs to be updated, use apt-get install -y foo to update automatically.

I am skeptical of this advice, overall.

I agree that it's not good advice to put `RUN apt-get upgrade` line in your Dockerfile, because if packages needed to be upgraded then your Docker image is going to be expanded by old, irrelevant versions stored in previous layers of the image.  But if you want to get a package post-install script to trigger, there is no easier way than to install the upgraded version of that package.

OK, so MySQL is apparently a bad example, because the advice from official mysql docs says "`The MySQL server always restarts after an update by APT. Once the server restarts, you should run mysql_upgrade to check and possibly resolve any incompatibilities between the old data and the upgraded software.`"  So in reality, it looks like if you needed to run `mysql_upgrade` then dpkg wasn't going to do it for you anyway.

Regardless, if I have a database container to be upgrading, I am going to start with apt-get because I don't know what is in that post-install script, and it might be important.  If you told me I couldn't use `apt-get upgrade` to update my packages, I'd probably go out and download them manually and use `dpkg -i` to do it.  (Which isn't really improving much of anything...)

I'm just leery that not allowing these post-install scripts to run every time the package version is changed, inside of the running container, connected to the database volume, ... is asking for trouble.  To complete the upgrade I would take that container and attach it to a freshly built image!

The root of the issue was that MySQL and similar packages can't even be restarted by any process that depends on invoke-rc.d.  We've strayed far from that issue in this discussion.  Is there a change that we can make, so that invoke-rc.d somehow does the right thing?  I'm sadly skeptical of that too.

**Comment by twobombs** [comment]
On a late note: stopping the (mysql)service before the upgrade fixes this behavour; the script checks if the service is down, if it's down before starting the upgrade this issue is rendered moot at that time.

**Comment by marto** [comment]
The discussion of this ticket has some what deviated from the original bug around logrotate not functioning. Most of the logrotate scripts shipped with ubuntu 18.04 (baseimage-docker v 0.11) are now not working unless you actively fix the ``/etc/logrotate.d/xxx`` scripts and make them runit  aware. A good example is log rotation of apache2 logs. 

It wouldn't take too much to create an ``/usr/sbin/invoke-rc.d}`` bash script and make it runit compatible. It's part of (https://launchpad.net/ubuntu/bionic/+package/init-system-helpers).

There could be other integration that rely on ``invoke-rc.d`` and reloading/restarting services.
