### ISSUE TITLE
my_init.d scripts and run issues

### ISSUE THREAD

**Issue by thegregthomp** [phusion/baseimage-docker#228]
Hey guys, so I followed your example for logging the time to a file and I noticed that it only works when you use run as a daemon. If I use run like so: 

docker run -i -t -p 80:3000 --rm --name test -v $DIR/app:/Development my_image bash -l

the script will run but will not create the file. If I use run like so:

docker run -d -p 80:3000 --name test -v $DIR/app:/Development my_image

and the use docker exec -it test bash, it works, wrote the file and everything. Any ideas why? Thanks!

**Comment by yebyen** [comment]
To guess based on your description, I can't really guess because I'm not sure what example you followed.  I didn't see any logging guides in the front-page README.md so it might help to include more information in your report.  What guide did you follow?  What file were you expecting to see written exactly?

But, based on my understanding of how logging works in Docker _in most cases_ now you are being instructed to let your application's logging send its output straight to stdout, and let Docker find them there (where they can be made available for tail or reading in `docker logs`).

When you run a container with `-it` you are sending stdout directly to the terminal (`-i` interactive `-t` terminal).  This way probably nothing really goes to docker logs, it's all printed to your interactive session as long as you are still attached to it.

Hope this helps you out.

**Comment by cardoe** [comment]
@thegregthomp I'm seeing the same issue and I expected it to work with `-t -i` as well.

@yebyen The issue is if you follow the steps from https://github.com/phusion/baseimage-docker#running_startup_scripts then your script will not run if you use `-t -i` to `docker run` but if you use `-d` it works.

**Comment by cardoe** [comment]
The issue is that the default command is `/sbin/my_init` via the `CMD` declaration in the `Dockerfile`. It is not an entrypoint so when you (and I) are specifying `bash -l` on the command line we are replacing the execution of `/sbin/my_init`.

**Comment by FooBarWidget** [comment]
This is probably a documentation issue.

**Comment by Theaxiom** [comment]
I added the following to the README.md:

*Important note:* If you are executing the container in interactive mode (i.e. when you run a container with `-it`), rather than daemon mode, you are sending stdout directly to the terminal (`-i` interactive `-t` terminal). If you are not calling `/sbin/my_init` in your run declaration, `/sbin/my_init` will not be executed, therefore your scripts will not be called during container startup.
