### ISSUE TITLE
Keep updated python 2.7.X

### ISSUE THREAD

**Issue by antonbormotov** [phusion/baseimage-docker#229]
Guys,
I would like to contribute to this image with PR.
How can we update to the latest version of python 2.7.X inside this based image?
Currently, it is 2.7.6, but latest version is 2.7.10.
Do we need to add PPA repositories?
Could you please tell me, how can I do this?
Thank you very much.

**Comment by yebyen** [comment]
I went looking on http://packages.ubuntu.com/trusty/python to see what the latest version of Python is in 14.04, and it appears to be 2.7.5.  This will necessarily be the latest version available in baseimage-docker built on trusty, as it is.

Because of long-term stability, phusion builds baseimage-docker on 14.04 trusty (LTS).  This will probably not change before 2016 April when 16.04 (the next LTS) is released.  On the other hand, you are welcome to add PPAs to your derived containers to get the latest release, build your own baseimage-docker as I have done on top of a newer Ubuntu image (vivid 15.04 has a package for Python 2.7.9), or there may be other alternative solutions that I have not considered.

Those would be your best bets, though.  In my case, I needed baseimage-docker to be built on top of an i386 image of ubuntu:trusty, which I could not find, so I built it using mkimage-debootstrap.sh from upstream, changed Makefile and Dockerfile just a little bit, and rebuilt.

https://github.com/phusion/baseimage-docker/compare/master...kingdonb:i386

The important line to update is in `Dockerfile`:
```
FROM ubuntu:14.04
```
You can change the 14.04 tag to 15.04 `vivid` or 15.10 `wily`, just know that even unreleased 15.10 does not have the latest version of python that you asked for.

NB: building baseimage-docker on a newer Ubuntu release would probably be classified as doing something unsupported.  I can probably guarantee you won't be the only one doing it, so if you have issues, I'd still advise to bring them back here; just with the knowledge that you're doing something unsupported.

**Comment by FooBarWidget** [comment]
It is pretty much as yebyen said. We only support Ubuntu 14.04 because we favor stability over features. If you want a newer Python, you should build baseimage-docker on top of a newer Ubuntu, or use some PPA.
