### ISSUE TITLE
Override Default KILL_PROCESS_TIMEOUT

### ISSUE THREAD

**Issue by nritholtz** [phusion/baseimage-docker#242]
I am currently running delayed_job as a svc in runit. However by default when shutting down delayed_job via SIGTERM, it sends a shutdown sequence that allows all "in process" jobs to finish before shutting down the process.

To allow this behavior to work in the case of a `docker stop`, I have written a `control/t` script to send a `kill -15` and wait till process finishes or 60 seconds pass (whichever comes first), in which case it will then send a `kill -9`.

However, I'm finding that about 10 seconds in the container exits with an exit code 137. Is it possible that this is due to the KILL_PROCESS_TIMEOUT? In which case is there some way to override it?

**Comment by FooBarWidget** [comment]
`KILL_PROCESS_TIMEOUT` defaults to 5 because `docker stop` has a default timeout of 10 seconds. If `my_init` doesn't kill processes within 10 seconds, Docker will do it for you.

So yeah, you can modify `KILL_PROCESS_TIMEOUT` in `my_init` beyond 10 seconds, provided that you *also* increase the `docker stop` timeout.
