### ISSUE TITLE
Way to have logging just go to stdout?

### ISSUE THREAD

**Issue by rberger** [phusion/baseimage-docker#248]
I'm trying to run the docker containers on Mesos and it would be much better if all the logs when to stdout or stderr. 

Is there a way to have my_init or basimge-docker do that?

**Comment by FooBarWidget** [comment]
No, because this sort of functionality is to be configured in the applications. Applications tend to log to a log file. What you need to do is to either configure them to do one of the following:

 1. To log to stdout/stderr
 2. To log to syslog
 3. To create a service that tails the logfile, thereby redirecting logs to stdout/stderr.

For example, baseimage-docker by default provides a service that redirects syslog to stdout. This is why (2) works. See https://github.com/phusion/baseimage-docker/blob/master/image/services/syslog-ng/syslog-forwarder.runit
