### ISSUE TITLE
Nginx and php5-fpm respawning after 0.9.10?

### ISSUE THREAD

**Issue by rtgoodwin** [phusion/baseimage-docker#253]
Hi! 

I had been pinned to baseimage:0.9.9, and 0.9.10, with a container that has nginx and php5-fpm installed (among other things), and all was well. However, after moving to to 0.9.11 or above, nginx and php5-fpm are respawning constantly (and of course errors about ports in use because of it), and the only way I could fix it was to move from the existing/"standard" exec /sbin/nginx and php5-fpm runit invocations to the "daemon no" and "nodaemonize" options. 

It seems like most examples, including passenger images, don't have to go to that length, and I'd like to figure out what might have changed after 0.9.10 that would have necessitated these changes. It seems like Upstart might be interfering?  Here's the current "working" code (but keep in mind there are probably plenty of other poor practices, though I hope not! :) ) I'd like to just track down what maybe changed in baseimage and how to properly deal with it. 

Thanks!

https://github.com/rtgoodwin/spotweb-docker

**Comment by FooBarWidget** [comment]
All changes are documented in the changelog. I don't see any changes that may cause this issue though.

But Nginx and php5-fpm are *supposed* to run with 'nodaemonize' or equivalent. That's how runit works: the daemon must not daemonize so that runit can supervise it. If you ask me, I'm surprised that it at all worked for you pre-0.9.11.

**Comment by rtgoodwin** [comment]
Fantastic! Almost all of the examples I found related to runit/nginx didn't use the nodaemonize, so I thought I was in the wrong. Closing this, and thanks!
