### ISSUE TITLE
Cannot start baseimage on 32bit host

### ISSUE THREAD

**Issue by klaszlo** [phusion/baseimage-docker#270]
Is phusion/baseimage 64bit only? I would like to fire up the image on an old i686 server.
I just installed ubuntu 15.10 server edition,
this command executes successfully:

    docker run -t -i 32bit/ubuntu:14.04 /bin/bash

But this one fails: 

    docker run -t -i  phusion/baseimage:latest /bin/bash

    FATA[0000] Error response from daemon: Cannot start container 
    d896493911253031d0d35d579977ec59e95e95e4ee305c845551b2e658b5bc25: 
    [8] System error: exec format error 

Any pointer is much appreciated.

**Comment by FooBarWidget** [comment]
> Is phusion/baseimage 64bit only?

Almost all of Docker is 64-bit only. There are very few images out there that are 32-bit. None of Docker's official images are 32-bit. For our baseimage, we didn't bother making a 32-bit version.

**Comment by klaszlo** [comment]
If there is a guide somewhere, or you are willing to guide me, I would try to build an 32 bit image.
Since 32bit ubuntu image is available (14.04), it may be possible.

**Comment by kingdonb** [comment]
I have built and used my own 32-bit images of baseimage-docker, it's something that every 32-bit docker user is going to need to be prepared to do (if they are building anything on their docker, it will usually be necessary to build most of the stack for themselves.)

Step one for me, at least, is to bootstrap my own ubuntu images (rather than using the released ones), with `mkimage-debootstrap.sh` from Docker upstream.  Since nobody is building anything for you in 32-bit docker userland, and on these older systems it generally pays to save as much space in each layer as you can.  So as you necessarily perform `apt-get upgrade` before most package installations during any subsequent build, the upstream layers can save you from adding detritus by being kept fresh, as far up the stack as possible.

I tracked changes from `phusion/baseimage-docker` and rebased onto it for a while at [kingdonb/baseimage-docker](/kingdonb/baseimage-docker) for my own use, but it was not long before a bug in 32-bit docker that was not getting any attention caused me to lose interest in doing this and stop maintaining it.  YMMV.

You can see the really [small set of changes](https://github.com/phusion/baseimage-docker/compare/master...kingdonb:i386) I found I needed to make for my use case, all of them are not platform-specific and some of them may already have been added upstream in `phusion/baseimage-docker`.  The biggest thing is to remember you need to call your personal copy something other than `phusion/baseimage-docker` so nobody ever gets confused about it, unless of course you are actually FooBarWidget.

For the most part, change the name and version as needed in the `Makefile` as I have done, set your preferred upstream in the `Dockerfile` whether that's a stock ubuntu 32-bit or your own build, and you'd be good to go.

You can use this technique to try building your own baseimages on newer versions of Ubuntu from Canonical as well.
