### ISSUE TITLE
[16.04] no more sudo ?

### ISSUE THREAD

**Issue by allan-simon** [phusion/baseimage-docker#321]
I have a set of environment development docker image based on this image, and my build rely on `sudo` which seems to be no more existing since the update to 16.04. Is it on purpose?(as I can't see it in the changelog) if so could it be possible to know the rational and the workaround (i.e if it's because it can cause security issue, I will not try to install sudo myself for example :) )

**Comment by FooBarWidget** [comment]
Baseimage-docker is meant to be minimal. It only installs the bare minimum it needs. The fact that sudo is not installed by default means only that: it is not installed by default. It is not removed on purpose. It install it yourself i you want to. The fact that it was installed by default on previous versions was probably because some package dependend on it, not because it was consciously included.

**Comment by allan-simon** [comment]
ok, no problem, perfectly make sense. thanks for you answer :)
