### ISSUE TITLE
`netbase` not present in 0.9.19

### ISSUE THREAD

**Issue by ocramz** [phusion/baseimage-docker#323]
It makes the C `getprotobyname(3)` function fail, therefore tools such as Haskell `stack` fail.

To reproduce : 

```
$ docker run --rm -t -i phusion/baseimage:0.9.19 /sbin/my_init -- bash -l
# getent protocols tcp; echo $?
2
# ls /etc/protocols
ls: cannot access '/etc/protocols': No such file or directory
```

**Comment by Blaisorblade** [comment]
👍 For completeness: also the proper API on top of `/etc/protocols` fails:
```
# getent protocols tcp; echo $?
2
```

**Comment by Theaxiom** [comment]
This can be solved by installing the `netbase` package. I don't really know if this would be in the scope of the project for it to be provided in the base image.

**Comment by pRiVi** [comment]
Of course! It doesn't mean anything to break all C software which calls getprotobyname(3) by default.

Translation: We are the whale, we are so braindead that we don't feel any pain at all.

**Comment by kingdonb** [comment]
You'll catch more flies with honey;

netbase and its dependencies will represent about 300kb uncompressed files added to the image footprint, or close to 40kb compressed.  That's pretty slim, if there's value in it, but I don't know what software calls getprotobyname or why I need to support it baked into my image by default.

Surely those packages you might install which require netbase, will themelves depend on netbase if it's necessary and appropriate, won't they?  Can you provide a specific example and what is this function call for, @pRiVi ?  (Specifically what I'm asking, I guess: Are there any packages or binaries included in the baseimage today, that don't work because of this missing dependency?)

**Comment by kingdonb** [comment]
Apologies, I see an example was already provided -- "getent protocols" is something

I was genuinely interested in this C function you mentioned though, just because `getent protocols` provides a reasonably clear response doesn't mean it will always manifest as an error message that your clients will present clearly explaining.  It's clear there's some frustration here, and it would help the case for adding `netbase` if you'd explain yourself in some more detail.  Short of encouraging you to vent your struggles... what software expected netbase and how were you installing it?

In any case, installing package such as "netbase" for yourself is a well-documented way to resolve this in your child images.

**Comment by pRiVi** [comment]
Yeah, of course, you're right, I apologize.

A working Linux API on a linux system is nothing a program should rely on. And who is still using code based on C? Just unteachable rednecks do such braindead stuff.

**Comment by pRiVi** [comment]
Sorry for this reaction, but it feels for me very arrogant to design a software systems and not knowing POSIX and the fundamental basic concepts of using its surfaces.

By removing this file you just broke POSIX and C library standard in a so fundamental way that I just please you to learn about the history of unix and its standards, and then ask this question again.

We are standing on the shoulders of gigants - and you seem to me not be aware of this, damage it and are not aware how unrespectful this is in my eyes.

**Comment by Blaisorblade** [comment]
@kingdonb The original bug report probably did not make this clear, but IIUC, this package is required to support standard networking services, such as establishing TCP/IP connections.

Without this file, this image does not conform to the POSIX standard. And conforming to POSIX is a pretty low bar — IIUC Windows passes that technically.

> Surely those packages you might install which require netbase, will themelves depend on netbase if it's necessary and appropriate, won't they?

No, just like because they assume they are installed on a POSIX system, so they don’t need to depend on each of the packages needed for basic services. Maybe glibc should depend on this package, but it doesn’t. But this is part of the base system anyway.

@pRiVi Nobody has time to learn all that somebody else finds fundamental. Since you challenge competence, I have quite a few commits in the Linux kernel, and I have a BSc, MSc and PhD in CS (and with pretty high marks), and I understand this is a problem, but I don’t know exactly what standards govern minimal implementations, in theory and in practice. More specifically, I don’t even know if *all* software that uses standard networking breaks, or if it this varies depending on whatever factor. The authors aren’t sure either, and few users have complained.

What’s weirder, the original report mentions stack, which is overall a pretty niche software (and I say that as a contributor to stack). So, if other networking software gets by, maybe it’s better for enough users to have a non-conforming system to save space.

**Comment by pRiVi** [comment]
@Blaisorblade The incompetence here is nothing about kernel commits or not, or which degree somebody hat, but about practice. And the working in a way trying to not break anything well defined as standard. So in this sight I think @kingdonb is more capable of doing right, cause he is just doing things he did not look around - overestimation of one's own capabilities. Not only a bad type of working together, has also benefints. But you seem to be a guy just wanting to define breaking stuff as a kind of sacrifying that breaking is a good thing at all. I would not like to work with you together, in this case I would prefer @kingdonb .

**Comment by Blaisorblade** [comment]
FWIW, I’m not a maintainer here, just a user who run into this bug earlier. I saw @kingdonb asked you questions, you challenged their competence instead of answering, and I tried to convince you to answer their questions and contribute some answers of my own.

And I only mentioned my qualifications to convince you the answers are not obvious. I shouldn’t have done that anyway.

> aksing others knowing more than yourself

You seem to know more, @kingdonb did ask, and you just vented instead of answering, even after @kingdonb has replies more than graciously to your venting.

FWIW, what still puzzles me in the image is that it provides SSH, so somehow this doesn’t break all network software. I’d hoped to get insight, but I’m not going to try again.

**Comment by pRiVi** [comment]
My point is not fixing a break of standards a way that something may works or not. I am just interessted to tell you not breaking POSIX without need, and that there is no alternative to undo this. I can not see any need to find out why ssh or something else is working:

_If you break standards without need you are lost - nothing more to discuss._

**Comment by kingdonb** [comment]
I didn't know the POSIX standard.  I'm convinced, myself

300kb is nothing, and we inherited this repo!

**Comment by kingdonb** [comment]
> Not knowing is not an excuse or cause to break things. It is a need to learn, get to know and not to break without a need.

We ask for tests first, and then we merge patches if it makes sense.  We didn't break anything by perpetuating the status quo.  We saved 300kb by leaving things they way they were.  This is the first time I've heard anyone explain why those 300kb are important to include.

We should put some references on this thread.

**Comment by pRiVi** [comment]
I hope that I was too nonsensitive, I think I were a little bit too much pissed off.

**Comment by kingdonb** [comment]
None taken! I don't want to seem stalwart in standing my ground either. It's a trade-off, and it's hard to calculate for all people. Baseimage has over 5MM pulls and a footprint of 68Mb in the latest release. So assuming the image has never had netbase, that means 1.5TB of transfer has been saved. On the other hand, POSIX.  Well let's just say I've seen this play out before, so bear with me.

I found this: http://wiki.lustre.org/POSIX_Compliance_Testing

I'm going to run this against the latest release, 0.11, and see what it says.

Meanwhile I also found this thread: https://ubuntuforums.org/showthread.php?t=918336 which seems to say that Ubuntu itself is not certified POSIX compliant, but you can add POSIX to it.  Someone suggested the "lsb" package will achieve this.  I see that "lsb" is divided into `lsb-core` and `lsb-printing` – let's assume that printing is irrelevant to the subset of POSIX that we're interested in for containerized servers, and just check the size of lsb-core and its dependencies (which does seem to include netbase, transitively, but only as a "recommended" package)

```
Recommended packages:
  build-essential fakeroot gnupg | gnupg2 libalgorithm-merge-perl manpages manpages-dev libcupsfilters1 libfile-fcntllock-perl
  liblocale-gettext-perl libarchive-cpio-perl libltdl-dev netbase libmail-sendmail-perl
The following NEW packages will be installed:
  alien at autoconf automake autopoint autotools-dev bc binutils binutils-common binutils-x86-64-linux-gnu bsdmainutils cpio cpp cpp-7
  cups-bsd cups-client cups-common debhelper debugedit dh-autoreconf dh-strip-nondeterminism dpkg-dev ed file gcc gcc-7 gcc-7-base gettext
  gettext-base groff-base guile-2.0-libs intltool-debian libarchive-zip-perl libarchive13 libasan4 libatomic1 libavahi-client3
  libavahi-common-data libavahi-common3 libbinutils libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libcroco3 libcups2 libcupsimage2
  libdpkg-perl libdw1 libelf1 libfile-stripnondeterminism-perl libfribidi0 libgc1c2 libgcc-7-dev libgdbm-compat4 libgdbm5 libgomp1
  libgsasl7 libicu60 libidn11 libisl19 libitm1 libkyotocabinet16v5 liblsan0 libltdl7 liblua5.2-0 liblzo2-2 libmagic-mgc libmagic1
  libmailutils5 libmpc3 libmpfr6 libmpx2 libmysqlclient20 libnspr4 libnss3 libntlm0 libperl5.26 libpipeline1 libpython2.7
  libpython2.7-minimal libpython2.7-stdlib libquadmath0 librpm8 librpmbuild8 librpmio8 librpmsign8 libsigsegv2 libtimedate-perl libtool
  libtsan0 libubsan0 libxml2 linux-libc-dev lsb-core lsb-invalid-mta lsb-security m4 mailutils mailutils-common make man-db
  multiarch-support mysql-common ncurses-term patch pax perl perl-modules-5.26 po-debconf rpm rpm-common rpm2cpio rsync time xz-utils
The following packages will be upgraded:
  gcc-8-base libgcc1 libstdc++6 perl-base
4 upgraded, 116 newly installed, 0 to remove and 57 not upgraded.
Need to get 61.8 MB of archives.
After this operation, 277 MB of additional disk space will be used.
```

Yikes! And here's the budget for `lsb-core` with recommends:

```
9 upgraded, 146 newly installed, 0 to remove and 52 not upgraded.
Need to get 77.5 MB of archives.
After this operation, 329 MB of additional disk space will be used.
```

Not to fall victim to the slippery slope argument, recalling what you came here asking for:

```
# apt-get install netbase
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  netbase
0 upgraded, 1 newly installed, 0 to remove and 61 not upgraded.
Need to get 12.7 kB of archives.
After this operation, 45.1 kB of additional disk space will be used.
```

So then, we really are talking about 45kB for netbase, and not all of POSIX.  Now 1.5TB seems like a modest bandwidth spend compared to the doubling or greater in archive size that would come from making baseimage POSIX compliant, assuming that's what lsb-core will do.

I'm sure someone did this analysis before, and you can find it in the issues history, but they were not asking for "netbase" specifically (evidenced that this issue is the only one that pops up when you search GitHub issues for this repo.)

But then so you can understand how this decision was made, without prejudice... you can refer to https://github.com/phusion/baseimage-docker/blob/master/image/prepare.sh#L41

and https://github.com/phusion/baseimage-docker/blob/master/image/Dockerfile#L1

We only provide "Ubuntu base", upgraded at release time with `--no-install-recommends`.  And now hopefully you can see exactly how installing the netbase package got overlooked.  With what Ubuntu thinks belongs in a minimal container image, in system-services.sh we add Runit, syslog-ng, sshd, and cron.  Facilities are provided to skip any of those at build-time, if you know you won't need them.

This is a minimal base image.  I don't have a hard time with 45kB, I just don't know exactly where it fits.  I appreciate your position.  It would be more convincing for me if we could point at something else that is already in the image, that doesn't work because netbase is missing.

I'll look at the POSIX compliance, but I can also promise we won't be adding all of `lsb-core` to the base image, since users downstream can always install that.

**Comment by kingdonb** [comment]
This is interesting:

```
# apt install --no-install-recommends build-essential
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu cpp cpp-7 dpkg-dev g++ g++-7 gcc gcc-7 gcc-7-base libasan4 libatomic1 libbinutils
  libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libdpkg-perl libgcc-7-dev libgdbm-compat4 libgdbm5 libgomp1 libisl19 libitm1 liblsan0 libmpc3
  libmpfr6 libmpx2 libperl5.26 libquadmath0 libstdc++-7-dev libtsan0 libubsan0 linux-libc-dev make patch perl perl-modules-5.26 xz-utils
Suggested packages:
  binutils-doc cpp-doc gcc-7-locales debian-keyring g++-multilib g++-7-multilib gcc-7-doc libstdc++6-7-dbg gcc-multilib manpages-dev
  autoconf automake libtool flex bison gdb gcc-doc gcc-7-multilib libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan4-dbg
  liblsan0-dbg libtsan0-dbg libubsan0-dbg libcilkrts5-dbg libmpx2-dbg libquadmath0-dbg glibc-doc gnupg | gnupg2 git bzr gdbm-l10n
  libstdc++-7-doc make-doc ed diffutils-doc perl-doc libterm-readline-gnu-perl | libterm-readline-perl-perl
Recommended packages:
  fakeroot gnupg | gnupg2 libalgorithm-merge-perl manpages manpages-dev libfile-fcntllock-perl liblocale-gettext-perl netbase
The following NEW packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu build-essential cpp cpp-7 dpkg-dev g++ g++-7 gcc gcc-7 gcc-7-base libasan4 libatomic1
  libbinutils libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libdpkg-perl libgcc-7-dev libgdbm-compat4 libgdbm5 libgomp1 libisl19 libitm1
  liblsan0 libmpc3 libmpfr6 libmpx2 libperl5.26 libquadmath0 libstdc++-7-dev libtsan0 libubsan0 linux-libc-dev make patch perl
  perl-modules-5.26 xz-utils
0 upgraded, 41 newly installed, 0 to remove and 0 not upgraded.
Need to get 41.6 MB of archives.
After this operation, 199 MB of additional disk space will be used.
```

Even for the build-essential package, netbase is only recommended and not considered by Ubuntu as a hard dependency.

**Comment by kingdonb** [comment]
After reading the definition of "recommends" I see why there is pain here.  But this baseimage historically has used no-install-recommends by default.

You can use the documented "install_clean" with --install-recommends in your child image, when you are installing `build-essential`, and this will be included.  For now, this is the state of things.  We can reopen this discussion if there's interest in adding netbase or other recommends in the next minor release.

It seems like there is a slippery slope though; my other PaaS project has recently swapped out the slimmer `heroku/heroku:18` runtime image for `heroku/heroku:18-build` in order to support the new MJIT in Ruby 2.6: https://github.com/teamhephy/slugrunner/pull/8/files

That would be an extreme change for baseimage-docker.  I won't make a decision about netbase until I see a POSIX suite output, also please remember I'm not the only, or even primary maintainer here.  If it's really a choice between 45kb and more POSIX compliance, I'm leaning toward POSIX.
