### ISSUE TITLE
Remove KILL_PROCESS_TIMEOUT or make it modifiable

### ISSUE THREAD

**Issue by jsravn** [phusion/baseimage-docker#384]
`/sbin/my_init` should not be killing my process after some hard coded timeout. People are using orchestration tech like kubernetes, which manages these timeouts in an explicit way so things can gracefully terminate. The my_init behaviour of a hardcoded 5s is hidden away in the script and not documented or obvious, and causes problems in these environments.

Can we either remove it completely (preferred), or increase it / make it modifiable with a flag?

**Comment by kingdonb** [comment]
It looks like it already is modifiable with an environment variable.  https://github.com/phusion/baseimage-docker/blob/next/image/bin/my_init

The beginning of this script:

```
KILL_PROCESS_TIMEOUT = os.environ.get('KILL_PROCESS_TIMEOUT', 5)
KILL_ALL_PROCESSES_TIMEOUT = os.environ.get('KILL_ALL_PROCESSES_TIMEOUT', 5)
```

looks like it's pulling environment variables that you could set in the Dockerfile, but it is a bug that there is no documentation of this feature or how to use it anywhere in the README.  I think the correct way to do this right now is to build your own Dockerfile such as this:

```
FROM phusion/baseimage

CMD ["/sbin/my_init"]
ENV KILL_PROCESS_TIMEOUT 60
ENV KILL_ALL_PROCESS_TIMEOUT 60
```

I am not sure it makes sense to disable this feature entirely, it is the role of the process supervisor to clean up child processes and you can optionally disable supervision entirely (don't use my_init), if you have something else taking care of those concerns.  The process supervisor is actually broken if it never kills child processes.  You could add a flag to disable it, but I would make that a totally separate change because how to implement it inside of my_init probably warrants further discussion.

But moving those existing values to something like "values.yaml" or similar one-stop-shopping place for global configuration variables such as this to live, in the style of helm, is something I could immediately get behind.  Helm is not currently a dependency of this project at all, and it makes sense to keep this image as agnostic of orchestration tools as possible... so maybe not values.yaml, but something almost exactly like it for all configuration variables would be nice to have, and could potentially help to make the documentation smaller.

I am using Kubernetes too, and your criticism of this decision is pretty much spot-on.

**Comment by jsravn** [comment]
Ah it looks like that got changed very recently, https://github.com/phusion/baseimage-docker/commit/d9e762730a1c065cf3eac10d3435664edff44b61 in 0.9.20 version. Not sure this has been released yet though. Documentation update would be great as well.

**Comment by jsravn** [comment]
I don't mind it killing the child process, I just don't want it having a hidden timeout for it. Kubernetes and docker will force kill everything after its own timeout.

**Comment by kingdonb** [comment]
I think there is (was?) an issue with grandchild processes not getting cleaned up and turning into zombies if the process supervisor was killed or wasn't keeping track.  Not sure if Docker has evolved a more general solution to this, but it seems likely that the timeout was made short to avoid the case where the process supervisor was forcefully killed and did not have time to clean up child processes.

**Comment by Theaxiom** [comment]
This was released in 0.9.20 -- prior to that it could not be overridden.

**Comment by jsravn** [comment]
@Theaxiom It appears broken, unfortunately. When I set `ENV KILL_PROCESS_TIMEOUT=3600`:

```
Traceback (most recent call last):
  File "/sbin/my_init", line 308, in main
    stop_child_process(args.main_command[0], pid)
  File "/sbin/my_init", line 152, in stop_child_process
    signal.alarm(time_limit)
TypeError: an integer is required (got type str)
```

**Comment by jsravn** [comment]
`os.environ.get('KILL_PROCESS_TIMEOUT', 5)` should be `int(os.environ.get('KILL_PROCESS_TIMEOUT', 5))` probably.

**Comment by jsravn** [comment]
I made https://github.com/phusion/baseimage-docker/pull/385 to fix it.

**Comment by Theaxiom** [comment]
Ahh ok, we will have to change it to eval as int.

**Comment by Theaxiom** [comment]
Thank you, I will get this merged in asap.

**Comment by Theaxiom** [comment]
This also brings up how we should be pushing `next` to docker-hub for people who want bleeding edge updates.
