### ISSUE TITLE
Not able to find executables in path?

### ISSUE THREAD

**Issue by chrissound** [phusion/baseimage-docker#421]
I've tried install Apache as well as php-fpm, both run into the issue of: 
`Cannot start service apache: oci runtime error: container_linux.go:247: starting container process caused "exec: \"httpd-foreground\": executable file not found in $PATH"`

Dockerfile:
```
FROM phusion/baseimage:0.9.22

RUN apt-get update
RUN apt-get -y install apache2 libapache2-mod-fastcgi
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
CMD ["httpd-foreground"]
```

**Comment by kingdonb** [comment]
I'm sure Ubuntu doesn't provide an httpd-foreground binary, don't you want to use the runit init system? 🗡 

```Dockerfile
# Dockerfile
FROM phusion/baseimage:0.9.22

RUN apt-get update
RUN apt-get -y install apache2 libapache2-mod-fastcgi
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /etc/service/httpd
COPY httpd.sh /etc/service/httpd/run
RUN chmod +x /etc/service/httpd/run
CMD ["/sbin/my_init"]
```

```sh
# httpd.sh

#!/bin/sh
apachectl -d /etc/apache2 -f apache2.conf -e info -DFOREGROUND

**Comment by chrissound** [comment]
Thanks for the help, I suppose I could run `apachectly` directly (which works), and I'd be able to swap over to `my_init` if I ever require the additional services.

Thanks for that.

I'm not sure what is the executable for `php-fpm` (command line)?

**Comment by chrissound** [comment]
Ah I had a look at `/etc/init/php7.0-fpm.conf` which had: `/usr/sbin/php-fpm7.0 --nodaemonize --fpm-config /etc/php/7.0/fpm/php-fpm.conf`

**Comment by kingdonb** [comment]
@chrissound That looks good.  You can certainly call apachectl directly with the -DFOREGROUND, because something has to run in the foreground and prevent the container from exiting.  The `--nodaemonize` flag to php-fpm has the same effect.  If you need both processes running, it will definitely benefit you to use the my_init way, because you will have a way to restart either or both without also killing the running container.
