### ISSUE TITLE
Is ubuntu 17.04 on the way?

### ISSUE THREAD

**Issue by Filechaser** [phusion/baseimage-docker#424]
I would love to know if a 17.04 release is possible?
Can this one be updated? If yes, how?

Thanks for your support

Yours sincerely

Filechaser

**Comment by hyperknot** [comment]
The next LTS version will be 18.04, so I believe the project will wait till
then.

But feel free to change the Dockerfile to your liking and build it yourself.

**Comment by kingdonb** [comment]
@Filechaser Feel free to ask for help if you're having trouble building an image from a more current release.  The baseimage-docker project has historically supported only LTS releases, probably because the necessary upgrade frequency to keep up with security issues is so much lower.

Historically, I've also almost never used the LTS branch myself.  I usually prefer to build a fresh copy and against the 17.04 branch.

This is approximately the change you should make (substituting your own name), I'd recommend you do this before running `make build`:

```diff
diff --git a/Makefile b/Makefile
index 75196aa..83b4b8e 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
-NAME = phusion/baseimage
-VERSION = 0.9.22
+NAME = kingdonb/baseimage
+VERSION = 0.9.22-1

 .PHONY: all build test tag_latest release ssh

diff --git a/image/Dockerfile b/image/Dockerfile
index fdfaae1..622fcf3 100644
--- a/image/Dockerfile
+++ b/image/Dockerfile
@@ -1,4 +1,4 @@
-FROM ubuntu:16.04
+FROM ubuntu:17.04
 MAINTAINER Phusion <info@phusion.nl>

 COPY . /bd_build
diff --git a/image/fix_pam_bug.sh b/image/fix_pam_bug.sh
index ca4be4e..5006746 100755
--- a/image/fix_pam_bug.sh
+++ b/image/fix_pam_bug.sh
@@ -22,11 +22,11 @@ apt-get remove -y gdebi-core autoconf automake autopoint autotools-dev binutils
        groff-base intltool-debian libarchive-zip-perl libasan2 libasprintf0v5 libatomic1 \
        libaudit-dev libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libcrack2 libcrack2-dev libcroco3 \
        libdb-dev libdb5.3-dev libdpkg-perl libfile-stripnondeterminism-perl libfl-dev libgc1c2 \
-       libgcc-5-dev libgdbm3 libgomp1 libgpm2 libicu55 libisl15 libitm1 liblsan0 libmpc3 \
-       libmpfr4 libmpx0 libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libperl5.22 \
+       libgcc-5-dev libgdbm3 libgomp1 libgpm2 libicu57 libisl15 libitm1 liblsan0 libmpc3 \
+       libmpfr4 libmpx0 libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libperl5.24 \
        libpipeline1 libquadmath0 libselinux1-dev libsepol1-dev libsigsegv2 libstdc++-5-dev \
        libtimedate-perl libtool libtsan0 libubsan0 libunistring0 libxml2 libxml2-utils \
-       libxslt1.1 linux-libc-dev m4 make man-db patch perl perl-modules-5.22 pkg-config \
+       libxslt1.1 linux-libc-dev m4 make man-db patch perl perl-modules-5.24 pkg-config \
        po-debconf quilt sgml-base sgml-data w3m xml-core xsltproc xz-utils
```

There are no hard references to the version number anywhere else in the Dockerfile or build scripts so this is easy.  I tested this to make sure it builds (:-1:, needs this extra change that you might have tripped over if you already tried this).  I have not done any other testing on it, so if you run into problems like I said you can report them here, and I'll try to help.

This big blob of packages to uninstall in `fix-pam-bug.sh` is the part of the change that users are most unlikely to guess.  The dependencies have changed, and the blob unfortunately isn't written in a way to capture those dependencies (I'm not sure it's uninstalling the right list even now), it's just a temporary blob that is needed for far too long.  Unfortunately the LTS release cycle is just that long, the issue is obscure and not a security issue, so it doesn't come to attention of the LTS patch managers to be fixed in an update, and from the look of the timeline, the fix just barely didn't make it into Xenial Xerus at release time...

But, as a long time had passed since 2016-04 until the 17.04 release, I'd be willing to bet that now it's safe to remove `fix-pam-bug.sh` altogether from the image directory and from the Dockerfile, an easier change for users to guess.
