### ISSUE TITLE
syslog messages written to terminal

### ISSUE THREAD

**Issue by lukezaparaniuk** [phusion/baseimage-docker#429]
When I run an image locally, logging works as expected. However, when I run the same image on an Ubuntu EC2 instance (ubuntu-xenial-16.04-amd64-server-20170619.1 (ami-d15a75c7)), messages destined for `/var/log/syslog` are also written to the terminal. This includes the cron output. To prevent this, I've modified `/etc/syslog-ng/syslog-ng.conf` to:
```
filter f_syslog3 { not facility(auth, authpriv, mail, user, cron) and not filter(f_debug); };
```
This configuration file is otherwise unmodified. However, this prevents cron and user messages from ending up in `/var/log/syslog`, which is desirable as this file is shipped off.

Any ideas why this behaviour differs and how can I achieve user and cron logging to `/var/log/syslog` but not the terminal?

**Comment by gillez** [comment]
Hi,

I see the same behaviour as this.  In my terminal, running the docker image, I get messages from cron every 10 minutes:
Aug  7 13:05:01 803f1fe4f889 CRON[435]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Plus, every hour:
Aug  7 13:17:01 803f1fe4f889 CRON[495]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

These aren't really causing a problem but they do clutter up the console after it's been running for a while.  Any idea why these go to stdout rather than syslog?  As the OP suggested, I will also provide a modified /etc/syslog-ng/syslog-ng.conf, but is there another solution?

Thanks,
Giles

**Comment by jwilson8767** [comment]
To override rules you can create a file in `/etc/syslog-ng/conf.d/custom.conf`. For this particular case you can re-define the filter like so:
````
@define allow-config-dups 1
filter f_syslog3 { not facility(auth, authpriv, mail, user, cron) and not filter(f_debug); };
````
