### ISSUE TITLE
ar

### ISSUE THREAD

**Issue by gabrielnieves18** [phusion/baseimage-docker#440]

**Comment by Theaxiom** [comment]
What's this?

**Comment by gabrielnieves18** [comment]
I belive my cat walked in the keyboard while I wasnt around. Didnt realise he had opened an issue. My apologies!

**Comment by Theaxiom** [comment]
Hilarious!

On Oct 17, 2017 4:40 PM, "Zsolt Ero" <notifications@github.com> wrote:

Closed #440 <https://github.com/phusion/baseimage-docker/issues/440>.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/phusion/baseimage-docker/issues/440#event-1298016749>,
or mute the thread
