### ISSUE TITLE
How to install chrome upon this image?

### ISSUE THREAD

**Issue by ganlanyuan** [phusion/baseimage-docker#464]
I was trying to install upon this image:
```dockerfile
FROM phusion/baseimage:0.9.22

MAINTAINER William Lin <ganlanyuan@gmail.com>

USER root 

# Install utilities
RUN apt-get update --fix-missing && apt-get -y upgrade

# Install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && \
    apt-get install -y yarn wget

# Install Node
ADD nodesource/setup_8.x /tmp/setup_8.x
RUN bash /tmp/setup_8.x
RUN apt-get update && \
    apt-get autoremove && \
    apt-get install -y build-essential \
                       libfontconfig \
                       nodejs
                       
RUN \
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
  echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list && \
  apt-get update && \
  apt-get install -y google-chrome-stable && \
rm -rf /var/lib/apt/lists/*

# Set colume & working directory
VOLUME ['/www/web']
WORKDIR /www/

# Globally install gulp-cli, nodemon
# cache bust so we always get the latest version of LH when building the image.
ARG CACHEBUST=1
RUN yarn global add gulp-cli nodemon

# install packages
ADD package.json /tmp/package.json
ADD yarn.lock /tmp/yarn.lock
RUN cd /tmp && yarn 
RUN mkdir -p /www && cd /www && ln -s /tmp/node_modules
ADD package.json /www/package.json
ADD yarn.lock /www/yarn.lock

# commands run on container starts
ADD start.sh /www/start.sh
```
But when I ran Chrome programmatically, it always output this error (port may differ):
```
Error: connect ECONNREFUSED 127.0.0.1:46621
```
Am I missing something?

**Comment by kingdonb** [comment]
I'm interested in helping to solve this, as I'm using chrome and headless chrome in several container images and on Travis (but up to this point, not yet in baseimage-docker)

Off the top of my head, how are you starting Chrome?  (What's in `start.sh`)

I use xvfb to support Chrome with Selenium, and it starts as part of my test suite.  Cucumber calls Selenium which launches the app, and then Chrome (and optionally in headless mode.)  I'm pretty sure yours is different.  My sample config is here: https://github.com/Limnogirl90/gsl-usgs/blob/master/.travis.yml and the invocation of Chrome is buried deep inside of the `rake ci:tests` so, there's not much insight in this file, but if you're doing a similar thing you're welcome to browse around in that repo, bearing in mind that it hasn't actually been tested against baseimage.

**Comment by ganlanyuan** [comment]
Thanks @kingdonb 
I actually just run `gulp` command in `start.sh`. And in my `gulpfile.js` I run [lighthouse](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically) programmatically:
```javascript
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');
const ReportGenerator = require('lighthouse/lighthouse-core/report/v2/report-generator');
const log = require('lighthouse-logger');
const opts = {
  logLevel: 'info',
  output: 'html',
  chromeFlags: ['--show-paint-rects', '--verbose']
};

function launchChromeAndRunLighthouse(url, opts, config = null) {
  return chromeLauncher.launch({chromeFlags: opts.chromeFlags}).then(chrome => {
    opts.port = chrome.port;
    return lighthouse(url, opts, config).then(results =>
      chrome.kill().then(() => { return new ReportGenerator().generateReportHtml(results); }));
  });
}

gulp.task('lighthouse', () => {
  return launchChromeAndRunLighthouse('https://google.com', opts).then(results => {
    fs.writeFile('lighthouse/report.html', results, function(err) {
      if (err) { console.log(err); }
    });
  });
});
```

**Comment by kingdonb** [comment]
Those tools are foreign to me, but interesting.

I'll take a look with my own Rubyist TDD/BDD suite stack, and try your stack next if I don't see a common problem that we're both going to have.  I'm guessing that ECONNREFUSED is Chrome's remote access port for Lighthouse to control the browser.

It's either not listening for some reason on that port, or the address is confused, or third option I haven't thought of is possible.  I've just visited another issue where a user reported a documentation update that "localhost" is not always "127.0.0.1" because of IPv6.

If you can get the tool to pause before it would fail, check `netstat -ntul` for a list of ports that are open and listening.  I guess you want to make sure there's an open listener that would match the port you're trying to reach, otherwise it's clear why you're getting connection refused.

Try starting Chrome in standalone (headed) mode with xvfb as in:

```
xvfb-run -s "-screen 0 1280x1024x24" google-chrome
```

(you may need to install xvfb)

If it starts and keeps running in the virtual framebuffer without terminating, it's not a "Chrome won't start" problem, but some communication issue somewhere in your stack.  It will also help to look at the value in `chrome.port` and see if it matches the port that is reported as connection refused.

**Comment by Theaxiom** [comment]
Check out this issue where Chrome is installed in baseimage: https://github.com/phusion/baseimage-docker/issues/428

**Comment by ganlanyuan** [comment]
Thanks @Theaxiom 
Hey @kingdonb , I got the following issue when do `xvfb-run -s "-screen 0 1280x1024x24" google-chrome`:
```
[22:22:0202/155857.346213:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
``` 
Also got the same issue from `ChromeLauncher` when do `lighthouse` in the command line:
```
ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:40877 +1ms
ChromeLauncher:error Logging contents of /tmp/lighthouse.9zGKzyH/chrome-err.log +0ms
ChromeLauncher:error [21:21:0202/155237.024778:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
ChromeLauncher:error  +0ms
Unable to connect to Chrome
```
Do you have any suggestions?

**Comment by kingdonb** [comment]
> `Running as root without --no-sandbox is not supported`

This one looks pretty clear, Chrome does not allow the root user to run it without --no-sandbox.  Either use a non-root user, or don't use --no-sandbox.

Chrome is simply not starting because you've asked it to do something that is outside of its permissions model.  I'm really sorry that I haven't had a chance to try this with my own stack so I can't be more help yet, I am working my way back around to it.

**Comment by kingdonb** [comment]
This link might help.

https://blog.jessfraz.com/post/docker-containers-on-the-desktop/#5-chrome

It's not specific to baseimage-docker, but it has some guidance in case your Docker host is a Linux machine (so you can forward the sound and X11 display from the host machine into the container.)

This is another good link:

https://github.com/SeleniumHQ/docker-selenium

^ This one suggests forwarding /dev/shm into the container so that Chrome won't crash too often.

I have never had to use either of these tricks, but I use a third image that I've derived from Jenkins slave base in order to put Chrome inside a container for use with a Jenkins CI job (see the Dockerfile):

https://github.com/kingdonb/docker-jnlp-slave-ruby-runtime

Again I'm sorry I haven't been able to follow up with this specifically on baseimage-docker, but I do plan to come back to this soon.

**Comment by ganlanyuan** [comment]
Hey @kingdonb , thank you so much for your reply!
Seems the issue is not related to the baseimage. I tried with other images, but got the same issue. 
Thanks a gain for you great help!
Very appreciated!
