### ISSUE TITLE
set ENTRYPOINT instead of CMD

### ISSUE THREAD

**Issue by leorochael** [phusion/baseimage-docker#474]
In your README, you mention that people should test the `baseimage` (or images based on `baseimage`) by running:

    docker run -t -i <imagename> /sbin/my_init -- bash -l

You also warn people that if they forget to run `my_init` while calling `docker run` then their startup scripts won't work.

Why not just make the default `ENTRYPOINT` be `['/sbin/my_init', '--']`?

**Comment by pelly** [comment]
I also would like to know why `/sbin/my_init` isn't the `ENTRYPOINT`. Is there any harm in making it the entrypoint?

**Comment by kingdonb** [comment]
I'm not sure it follows the Principle of Least Surprise if your startup scripts are actually run when a user does

```
docker run -it <imagename> bash
```

Does anyone else agree?

**Comment by pelly** [comment]
Good point.

From my interpretation of ENTRYPOINT, it seems to be a wrapper that ensures
certain aspects of the environment are set up by default. Since the primary
reason I and using phusion/baseimage is for the startup goodies it
provides, I would have thought that my_init serves that purpose best as an
ENTRYPOINT, without requiring the user to know to call it if they want to
call "docker run".

Just the way I've internalized ENTRYPOINT, CMD and phusion/baseimage's
my_init so far... I'm somewhat new to Docker still, so I don't have as much
experience as you do.

**Comment by leorochael** [comment]
My interpretation of the Principle of Least Surprise is that when users do:

    docker run -it <imagename> bash

they expect `bash` to be running in the same context as whatever command would be run instead of `bash` if the user had only called

    docker run -it <imagename>

As such, I would expect initialization scripts to have been run.

The user can opt not to run the initialization scripts by overriding `--entrypoint`.

**Comment by kingdonb** [comment]
I can see both points of view.  I could get onboard with an entrypoint-based configuration, but since it could break peoples' existing workflows, it would probably be change that makes sense in semver to go into a major release (or at least minor release), rather than a patch-level release.

You are welcome to submit a PR and let's hear from some of the other contributors/maintainers!

**Comment by Theaxiom** [comment]
I am in agreement with @kingdonb :+1:

**Comment by bdod** [comment]
> I'm not sure it follows the Principle of Least Surprise if your startup scripts are actually run when a user does
> 
> ```
> docker run -it <imagename> bash
> ```
> 
> Does anyone else agree?

i am agree with you )

**Comment by Theaxiom** [comment]
Let's slate this for the next major release.

**Comment by kingdonb** [comment]
For what it's worth, these guys were some of my role models when I was a young computer growing up on the internet:

```
Developer(s) | Enlightenment development team
          -- | --
Initial Release: 1997; 21 years ago
Stable Release:  E22 0.22.2 / 15 March 2018; 6 months ago
```
