### ISSUE TITLE
unable to open supervise/ok: file does not exist

### ISSUE THREAD

**Issue by juvasquezg** [phusion/baseimage-docker#493]
Hi,

I have an warning message

I ran 

```
sv status sshd
```

I got

```
warning: sshd: unable to open supervise/ok: file does not exist
```

With new service too,

```
sv status api
```

I got

```
warning: api: unable to open supervise/ok: file does not exist
```

Dockerfile
```
FROM phusion/baseimage:0.10.1
```

Help me please,

Thank you.

**Comment by docquantum** [comment]
Hi juvasquezg. Can you give a little bit more info on your issue? Starting with possibly snippets of your docker file or a link to your project (if it's online).

I had a similar issue, it was because I had set the wrong path to my service file, so it got copied to the wrong location, thus runit wasn't able to find it. Your issue might be similar, a misplaced service file, or something totally unrelated.
