### ISSUE TITLE
Runit doesnt work (for me)

### ISSUE THREAD

**Issue by Joly0** [phusion/baseimage-docker#509]
Well, i try to make a Docke container for AMP (by CubeCoders) and tried everything i could, but i dont get it working, everytime i run my dockerfile, it exits instantly.
I cleaned my Dockerfile, so it is the absolute basic to make the whole thing atleast work.

Dockerfile:
FROM phusion/baseimage:master

RUN apt-get update && apt-get install -y openjdk-8-jdk-headless iputils-ping lib32gcc1 coreutils screen tmux socat git unzip wget libsqlite3-dev lib32stdc++6

EXPOSE 8080

RUN useradd -d /home/AMP -m AMP

RUN su AMP -c "wget http://cubecoders.com/Downloads/ampinstmgr.zip -O /tmp/ampinstmgr.zip"

RUN su AMP -c "cd /home/AMP; unzip /tmp/ampinstmgr.zip"

COPY script.sh /home/AMP/LaunchAMP.sh

RUN chmod 775 /home/AMP/LaunchAMP.sh

RUN su -c "rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/* "

CMD ["./home/AMP/LaunchAMP.sh"]

script.sh:

#! /bin/bash

LICENCE
PASSWORD /password
USERNAME /admin

su - AMP -c "printf 'Port: $PORT\nLicense: $LICENCE\nPassword: $PASSWORD\nUsername: $USERNAME'"

su - AMP -c "/home/AMP/ampinstmgr CreateInstance ADS ADSInstance 0.0.0.0 8080 $LICENCE $PASSWORD +Core.Login.Username $USERNAME"

su - AMP -c "/home/AMP/ampinstmgr StartInstance ADSInstance"

Does someone has an Idea, how i can solve this and what i have to edit, so the whole thing works with runit or doesnt exit itself. I know, i can just add something like "while true; do sleep 1000; done" at the end of my script, but thats not how i want it to work...

**Comment by kingdonb** [comment]
I don't think you've quite read all of the documentation about how to use runit...

https://github.com/phusion/baseimage-docker#getting-started

```
# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]
```

When you set your own CMD, you've just skipped starting runit altogether.  "my_init" is not meant to be replaced by your own init script.  That's the actual script that starts runit.

I'm not sure that the documentation around this is as clear as it should be.  I'm pretty sure that the next entry after Getting Started is what you want if you're trying to start a daemon, but it looks like you've got a script for that which you want to use.  I'm guessing that what you've tried didn't work because "ampinstmgr StartInstance" is not running as a daemon (if it was, you probably wouldn't have noticed that runit wasn't working.)

So, continue past that section to the next:

https://github.com/phusion/baseimage-docker#running-scripts-during-container-startup

```
The baseimage-docker init system, /sbin/my_init, runs the following scripts during
startup, in the following order:

* All executable scripts in /etc/my_init.d, if this directory exists. The scripts are run in lexicographic order.
* The script /etc/rc.local, if this file exists.
```

And there you have it.  Instead of copying `script.sh` to /home/AMP, try copying it to /etc/my_init.d/ instead.  Then make sure you've set the CMD to `/sbin/my_init` and set it to executable if necessary, then watch it run on container start.

With the CMD set correctly to invoke runit, you should see the other services like syslog and cron spin to life, and your script will execute, then runit will keep the container alive until you asked it to end.  The only disadvantage of running this way is that, scripts in /etc/my_init.d are "fire-once" so if ampinstmgr is not responsible for keeping the server alive (I think it's not), then runit won't be trying to keep it alive either.  This may be fine, and you might never notice a problem.  But...

You would probably be better off dissecting ampinstmgr to see how it starts the server, and then writing a runit service as described in the middle section we skipped past, "Adding additional daemons" – this is using the full power of runit.  If any runit service dies, if I remember correctly I think the behavior will be to stop the whole container.  If you're using some monitoring or container orchestration, the container will most likely be restarted then and your service will come back up.

Don't be afraid of writing runit services, they are just shell scripts and not complicated at all!  There is a comprehensive guide to runit at http://www.mikeperham.com/2014/07/07/use-runit/ and it's very brief.  The only important thing to remember is that the process that your runit script runs must not terminate, or it will be restarted.  In other words if you have a choice when running your application binary between running in "daemon" and "foreground" mode, choose foreground, since daemon will fork and exec in the background, as runit will detect that as a quit and think it needs to restart.

**Comment by Joly0** [comment]
Well, i think i was not clear enough, when pointing out my current stage. I tried this all, to a point, i understood it, but as u said, the documentation is not clear at some point and so i tried to figure it out by myself and was not able to get it working, so i resetted my whole dockerfile and script to a point, where it is as simple as possible and everyone would understand, what it does so noone gets confused by random things i tried to make it working. 

I read, what u wrote and will try it out, if i need aditional help, i will come back.

**Comment by Joly0** [comment]
Ok, checked it, and it seems to be working, more or less, the Docker Container stays alive, but the server itself doesnt. I went through the whole log and found this part:

[Debug] Working Directory: /home/AMP/.ampdata/instances/ADSInstance
[Debug] Arguments: +x "/home/AMP/.ampdata/instances/ADSInstance/AMP_Linux_x86_64"
[Debug] Started process with ID 52
[Debug] Building arguments list...
[Debug] Running AMP with configuration arguments...
[Debug] Starting process /home/AMP/.ampdata/instances/ADSInstance/AMP_Linux_x86_64


So it seems, that this process starts and stops the whole server, but now i dont know exactly, what i have to edit, to keep this process alive. Any Idea?

I tried to find something out about this deamon and foreground thing, but it seems like, its a deamon and there is no option to set it as foreground, so i guess, thats the reason, why it keeps shutting down everytime.

**Comment by kingdonb** [comment]
Did you try just setting that script +x and dropping it in /etc/my_init.d as-is?  That should have worked

**Comment by Joly0** [comment]
FROM phusion/baseimage:master

RUN apt-get update && apt-get install -y openjdk-8-jdk-headless iputils-ping lib32gcc1 coreutils screen tmux socat git unzip wget libsqlite3-dev lib32stdc++6

EXPOSE 8080

RUN useradd -d /home/AMP -m AMP

RUN su AMP -c "wget http://cubecoders.com/Downloads/ampinstmgr.zip -O /tmp/ampinstmgr.zip"

RUN su AMP -c "cd /home/AMP; unzip /tmp/ampinstmgr.zip"


COPY script.sh /etc/my_init.d/script.sh

RUN chmod +x /etc/my_init.d/script.sh


RUN su -c "apt-get clean && rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/* "

CMD ["/sbin/my_init"]


I did, but it didnt work, as i said, i can make it working by adding "while true; do sleep 1000; done" to the end of my script.

**Comment by kingdonb** [comment]
More specific when you say didn't work... do you mean it didn't run script at all, or didn't keep the AMP process running, ... or the container itself quit?  I'm going to infer that you meant it didn't keep the AMP process running (since you said it worked if you sleep at the end of your script), but please correct if I'm mistaken about any of this.

So, that's interesting.  Try this instead in your script maybe? :

```
su - AMP -c "exec /home/AMP/ampinstmgr StartInstance ....
```

If your script runs (you see the output from script.sh, indicating that it has run) but your service terminates, I'm thinking it might be the actual feature and exactly desired behavior of runit: the point of a pid 1 process: it should reap zombie processes.

What's a zombie?  Well, when you start a process that spawns other processes, then quits leaving them behind... that's a zombie process.  Normally they are left around until your container terminates, then cleaned up automatically by Docker.  In baseimage-docker (in runit), this is considered a misbehavior.  You are expected to write a service file for the long-running process, so that runit can keep track of it and restart the process if needed.

I did not know it would do this, but from everything you've explained I think that's what's happening.

**Comment by kingdonb** [comment]
(So I think the solution is, back to what I said at the beginning:

> dissecting ampinstmgr to see how it starts the server, and then writing a runit service

If ampinstmgr is inscrutable to you, try running it outside of a container, or examining the running container where you were able to get it running via sleep.  Look at the output of `ps wwwuax` and see if you can see what process it has left running behind.  That will give you a clue as to what your runit service script should do to get AMP running in the foreground, and leave ampinstmgr behind.

(Or, file a bug with AMP and ask them to provide an option for running in foreground mode.)

**Comment by Joly0** [comment]
Ok, i am really really dumb... It works now (or it seems like).

I always checked, if the webserver is working, by trying to load its website but somehow it never did, then i realised, that my docker run command was missing something and i remembered, that --network host was part of it but didnt at the moment i tested it, so i added it and started it with the script and dockerfile we both figured out would work and voila, website is reachable and everything seems to work....

**Comment by Joly0** [comment]
But you still helped me really out, i only managed to figure this out, by testing ps wwwuax and saw, that everything that should be running, was running, but the website was still not reachable.

**Comment by kingdonb** [comment]
Sounds like it's solved.  🎉 🌮 🥇
