### ISSUE TITLE
Update kill timeout documentation

### ISSUE THREAD

**Issue by jarischaefer** [phusion/baseimage-docker#517]
The documentation should be updated to explain the increased kill timeout (see [PR 510](https://github.com/phusion/baseimage-docker/pull/510)).

From [CONTRIBUTING.md](https://github.com/phusion/baseimage-docker/blob/master/CONTRIBUTING.md)
> The master branch is supposed to point to the latest stable release, because users read documentation from the master branch.

Should we update the documentation on the master branch despite the fact that the current release does not yet reflect the changes made in master? Perhaps a disclaimer should be added (e.g. "This change is only available on 0.11.1+").

**Comment by kingdonb** [comment]
Maybe something under the heading:
https://github.com/phusion/baseimage-docker/#shutting-down-your-process

Like, "Prior to 0.11.1, the default value for `KILL_PROCESS_TIMEOUT` was 5 seconds.  In version 0.11.1+ the default process timeout has been adjusted to 30 seconds."

Since it was always a user-configurable setting, I don't think language like "only available" makes sense.  (Opening a PR for this)

**Comment by kingdonb** [comment]
How does that look
