### ISSUE TITLE
SSHD should no password by default

### ISSUE THREAD

**Issue by DinoStray** [phusion/baseimage-docker#521]
always, I login container from host. 
If I can login host by root, there is no password need for container.
One container just one process, process should not have password!

By the way, how can I set no password login for baseimage

**Comment by caiojhonny** [comment]
You can put your public key into your Dockerfile:

First enable SSH:
```
RUN rm -f /etc/service/sshd/down

# Regenerate SSH host keys. baseimage-docker does not contain any, so you
# have to do that yourself. You may also comment out this instruction; the
# init system will auto-generate one during boot.
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh
```

Then copy your public key:
```
## Install an SSH of your choice.
COPY ./my_public_key.pub /tmp/your_key.pub
RUN cat /tmp/your_key.pub >> /root/.ssh/authorized_keys && rm -f /tmp/your_key.pub
```

After the build you can access your container from ssh:
ssh root@YOUR-SERVER-IP -p PORT_OF_YOUR_CONTAINER

**Comment by DinoStray** [comment]
> You can put your public key into your Dockerfile:
> 
> First enable SSH:
> 
> ```
> RUN rm -f /etc/service/sshd/down
> 
> # Regenerate SSH host keys. baseimage-docker does not contain any, so you
> # have to do that yourself. You may also comment out this instruction; the
> # init system will auto-generate one during boot.
> RUN /etc/my_init.d/00_regen_ssh_host_keys.sh
> ```
> Then copy your public key:
> 
> ```
> ## Install an SSH of your choice.
> COPY ./my_public_key.pub /tmp/your_key.pub
> RUN cat /tmp/your_key.pub >> /root/.ssh/authorized_keys && rm -f /tmp/your_key.pub
> ```
> After the build you can access your container from ssh:
> ssh root@YOUR-SERVER-IP -p PORT_OF_YOUR_CONTAINER

But I wanna build a Docker for all my partner. 
Everyone will use it freely.
Not just used by myself.
And no password or ssh key needed by this docker.

**Comment by kingdonb** [comment]
There are about 10 configuration settings you'll need to change in order to allow passwordless, unauthenticated root logins, because it's so dangerous, and I'm a little afraid of what might happen if we actually put that document together and someone decides to follow it blindly and then put it on the internet without understanding what they're doing.

You can set an empty password in /etc/shadow by using `passwd -d`: https://askubuntu.com/a/281085 — there's information in this link about enabling password-less sudo access.

You'll also need to separately configure SSHD to permit empty passwords for logins: https://superuser.com/a/384284

There's probably more... I haven't tested this.

For perhaps obvious reasons we don't want to make this configuration easy or put it on a silver platter, but there should be no reason you absolutely can't do it.  It's possible to secure this with a private network and properly configured firewalls.

Even a bad (dictionary) password is better than no password though.  I'd strongly suggest you agree on any password with your group of users, just write it on the whiteboard, otherwise simply put it will always remain possible that someone you don't want will find a way into your network and find some way to wreak havoc.

I'm closing this issue because there's absolutely no way we'll make this configuration the default.  Feel free to post again on this issue though if there's more information needed for your use case.

**Comment by BunnyHolder** [comment]
I just want to add, that easiest way to access your container is over `docker exec -it container_name_or_id bash` not compromising it's security.

**Comment by kingdonb** [comment]
The second easiest way, if you have Kubernetes API access, is over userland plugin:

https://github.com/mikelorant/kubectl-exec-user

née exec-user plugin
