### ISSUE TITLE
Where is the core dump file?

### ISSUE THREAD

**Issue by DinoStray** [phusion/baseimage-docker#524]
My application core dumped.
With baseimage-docker, where is the core dump file?

**Comment by kingdonb** [comment]
They would be in the container, if it hasn't crashed.  I'm reading that the default setting on Ubuntu is a ulimit setting of 0 for core size.

https://stackoverflow.com/a/18368068/661659

I just tested and on my system, "ulimit" already returns "unlimited" – so maybe this information is dated.  Check on your system to verify, it might not be something that is configured in the container.  I don't see any mention of `ulimit` in the Dockerfile or otherwise, so YMMV.

Second thing to check is, where is the kernel configured to write core files?

```
cat /proc/sys/kernel/core_pattern
```

Mine says "core" with no directory path prefix – so, I think that means the core file goes into the current working directory when the crash happens.  If your application's runit service sets a current working directory before executing the app, you should find the core file in that directory.

It will be in the container.  If your container has crashed (with baseimage configured with runit, it probably kept running and didn't crash, but I don't know how your image is configured), you can always take the crashed container, `docker commit` it to a new image tag (this will grab the final state of the container and make a new image from it), and then run something on that image.

(You may also commit a running container, AIUI) – the committed image will have the core file in it.

**Comment by DinoStray** [comment]
I found it locate /etc/service/xxx
