### ISSUE TITLE
"uname -n" return random number

### ISSUE THREAD

**Issue by DinoStray** [phusion/baseimage-docker#532]
If I run "docker exec -it xx bash"
then I can see 
root@3f3f768ae4a8:

and if I run "uname -n"
then I can see 
3f3f768ae4a8

what's the 3f3f768ae4a8 meaning

after I assign value to ${HOSTNAME}, there is stiil the random number

**Comment by Theaxiom** [comment]
That's the Docker container ID.

**Comment by kingdonb** [comment]
Since you cannot set the hostname in the /etc/hostname file in Docker, where you would traditionally set a hostname on a regular system, because it will be overwritten by the Docker container runtime... if you want to set the hostname then Docker provides `--hostname=value` option to the `run` verb.

```
docker run --hostname=value
```
OR 
```
docker run -h value
```

In a Kubernetes deployment manifest, I believe since you would set the container name in the pod spec, that becomes its hostname automatically.

I'm closing this because I think the question has been answered sufficiently.  Thanks all for participating.
