### ISSUE TITLE
Support latest non LTS versions?

### ISSUE THREAD

**Issue by dclong** [phusion/baseimage-docker#539]
It would be great if latest non LTS versions of Ubuntu (19.04 and 19.10 currently) are support.

**Comment by kzila** [comment]
Yes please.

**Comment by kingdonb** [comment]
I don't think we have the bandwidth for this, the point of supporting only LTS is that it is not a moving target.

But you can change the version and build your own image (which is intended to begin with).  If you find issues with later non-LTS versions that require changes, and you want to PR and upstream so that this can remain a simple one-line change, we will certainly consider merging them.  We are always looking for contributors.

**Comment by kingdonb** [comment]
I'm sure we could open a branch for the non-LTS and point CI at it ...

**Comment by Theaxiom** [comment]
We could TIAS what happens...

**Comment by Theaxiom** [comment]
Need to get CI working first

**Comment by Theaxiom** [comment]
Ci is now working, we can create a new branch. Which non-LTS release would you like to try first?

**Comment by dclong** [comment]
How about 19.10?

**Comment by dclong** [comment]
This might not be very useful since Ubuntu 20.04 is already out. But it helps in future when 20.10, etc. are released.

**Comment by samip5** [comment]
@dclong or @kzila Are you still interested in this?
