### ISSUE TITLE
how to change /etc/security/limits.conf 

### ISSUE THREAD

**Issue by DinoStray** [phusion/baseimage-docker#548]
My docker file:

`
FROM phusion/baseimage:0.11

COPY limits.conf /etc/security/limits.conf
COPY sysctl.conf /etc/sysctl.conf
`

The /etc/sysctl.conf is worked, but /etc/security/limits.conf is not valid.

**Comment by kingdonb** [comment]
What environment are you running your baseimage-derived images in?

I've never heard of doing this, my intuition is that your container orchestrator should set these limits, and enforce them on the container itself, from the outside.  In Kubernetes, you can do this with a request and limit on the pod spec for either memory or CPU.  The standalone docker also has its own provisions for making request/limit type constraints on launched containers.

https://docs.docker.com/config/containers/resource_constraints/

I've never used limits.conf and not sure how it works. Does it limit resources or capabilities, other than CPU and RAM? Would either of these alternative options work for your use case?

**Comment by DinoStray** [comment]
limits.conf limit resource by system, like ubuntu.

**Comment by kingdonb** [comment]
Got it, that makes sense. Can you share perhaps in a gist the settings files from your COPY directives?  If you're only trying to set max open files, I think I can replicate that on my own, but it will help to have the exact file that failed for you, even if that's all there is.

Some preliminary research I've done about setting max open files in a docker container reveals you're right, the container and the host each need to be adjusted, but it's not clear to me the container is adjusted via limits.conf.

https://stackoverflow.com/questions/26415833/docker-ignores-limits-conf-trying-to-solve-too-many-open-files-error/26415982#26415982

(Then also it follows that this is not a baseimage-docker issue, but I'm happy to help you solve it nonetheless)

If you are running Docker directly, you can set `--ulimit nofile=5000:5000` as described in this StackOverflow answer:
https://stackoverflow.com/a/43265224/661659

The answer beneath it suggests an alternative in case you are using Docker Compose, setting soft and hard limits on "nofile" through the compose file, which is the same setting as above.

The third option is of course to set `--privileged` which as one commenter noted is probably a terrible idea. I have no reason to believe that the container is configured in the same way as the external host machine config, I think these limits are imposed by the container runtime.

Since you haven't mentioned Kubernetes, I'm going to assume you aren't using it, (and that's good, because it looks like the story is more complicated on Kubernetes.) https://github.com/kubernetes/kubernetes/issues/3595 is an open issue way back since support for this feature landed in Docker/moby upstream back in 2015.

It seems like it has been left to languish because in Kubernetes architecture, you can't expose a new limit configuration for pod specs without also adding support to limit the range allowed in a PodSecurityPolicy, and my guess is that means some level of API changes makes this harder. There you can see people enabling "--privileged" as it was already established not to be a good idea...

**Comment by kingdonb** [comment]
I am closing this, I think I have answered your question. You can ask again if something is unclear, no need to reopen.

`/etc/security/limits.conf` is not meant to be edited from inside the container, but through your container runtime.
