### ISSUE TITLE
apt update not working

### ISSUE THREAD

**Issue by rene-demonsters** [phusion/baseimage-docker#549]
I'm trying to do a new Docker build for an existing project. The project uses `phusion/baseimage:0.11`. I decided to do a `--no-cache` build to update to the latest packages, but it keeps failing on `apt-get update`.

I've waited a few days to see if it was perhaps just some repository maintenance but it isn't. Below is the output of my docker build log:

```
Step 1/37 : FROM phusion/baseimage:0.11
 ---> 14e6c478b00a
Step 2/37 : CMD ["/sbin/my_init"]
 ---> Running in b31f613467fd
Removing intermediate container b31f613467fd
 ---> 1a2c73ae4c98
Step 3/37 : EXPOSE 80
 ---> Running in 5eae3f6b3b5d
Removing intermediate container 5eae3f6b3b5d
 ---> 4acd5a2c7a10
Step 4/37 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in 77c4e787cf19
Removing intermediate container 77c4e787cf19
 ---> a55b5fd09f8e
Step 5/37 : RUN curl http://nginx.org/keys/nginx_signing.key >> /tmp/nginx.key
 ---> Running in a1b767126928
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1561  100  1561    0     0  25590      0 --:--:-- --:--:-- --:--:-- 26016
Removing intermediate container a1b767126928
 ---> 256dd9042612
Step 6/37 : RUN apt-key add /tmp/nginx.key
 ---> Running in 9f216ed2e7fd
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Removing intermediate container 9f216ed2e7fd
 ---> e704fa231da7
Step 7/37 : RUN apt-get update
 ---> Running in 629184e545ea
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  At least one invalid signature was encountered.
Err:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  At least one invalid signature was encountered.
Err:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  At least one invalid signature was encountered.
Err:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://archive.ubuntu.com/ubuntu bionic InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu bionic-updates InRelease: At least one invalid signature was encountered.E: The repository 'http://archive.ubuntu.com/ubuntu bionic-updates InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu bionic-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-backports InRelease' is not signed.
W: GPG error: http://security.ubuntu.com/ubuntu bionic-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.ubuntu.com/ubuntu bionic-security InRelease' is not signed.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
```

**Comment by kingdonb** [comment]
I cannot repro this issue,

```
FROM phusion/baseimage:0.11
ENV DEBIAN_FRONTEND noninteractive
RUN curl http://nginx.org/keys/nginx_signing.key >> /tmp/nginx.key
RUN apt-key add /tmp/nginx.key
RUN apt-get update
```

I tried building an image with just the first and last lines of the dockerfile, because that key you added shouldn't have anything to do with the issue. It did apt-get update fine:

```
...
Get:31 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [2,496 B]
Get:32 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4,252 B]
Fetched 31.6 MB in 5s (6,097 kB/s)
Reading package lists...
Removing intermediate container 76494588b770
 ---> 8ebc19342543
Successfully built 8ebc19342543
Successfully tagged temp:latest
```

So I tried again following more closely what you did, with the inclusion of the extra step, adding a key from nginx.org, (as the Dockerfile above shows) and I still don't get any GPG errors.

Is it possible this is something unusual going on inside of your network?  (Is anyone else having this issue?)

**Comment by rene-demonsters** [comment]
There on no restrictions on such things on the network. To make sure I've actually tested this with and without VPN, but this didn't change the outcome. I've also untagged the image and pulled a new one, but no dice. 

I've decided to try this on a second machine and I actually don't see the issue either. `apt-get update` runs as normal. I guess it's time to reset my Docker install. I think something may have gotten corrupted when the Linux VM ran out of diskspace (Docker on Windows).

**Comment by kingdonb** [comment]
@rene-demonsters Please go ahead and close this if it turns out to be resolved by blowing away docker.

In fact, since it sounds likely that it is leaning that way, I'm going to go ahead and close right now, but please do let us know if that wasn't the solution.

**Comment by rene-demonsters** [comment]
Yep, blowing away Docker did the trick. Cheers! :)

**Comment by Excodibur** [comment]
FYI, I had the same issue with **phusion/baseimage:focal-1.0.0alpha1-arm**.

In my case I was trying to build a new Docker image on Raspberry 4, but kept getting the same errors as above. In additon, when running `date` command, I saw that the time within the container was wrong (1970) which perhaps is related to the signatures being invalid.

Looking further at this post (https://bugs.launchpad.net/cloud-images/+bug/1896443/comments/12) and other similar topics, it turns out, that libseccomp2 is currently bugged on RPI 4 and needs to be updated. After installing an updated library (e.g. [libseccomp2_2.5.1-1_armhf](http://ftp.uk.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb) via `dpkg -i` on my docker-host (not in container!) and restarting Docker service, it started to work.

**Comment by Theaxiom** [comment]
@Excodibur thanks for the update. Is there a way we can add this workaround to our build?

**Comment by Excodibur** [comment]
@Theaxiom Unfortunately I don't think there is much you can do in your build to avoid this (at least in my case), since the problem needed to be solved on my local server (RPI4) where I tried to build a new Docker image using yours as base-image. So to me it looks like the problem is not with the image you build at all. At some point I assume RPI4 will get a lib update and then the issue resolves by itself.

**Comment by Theaxiom** [comment]
Thank you @Excodibur
