### ISSUE TITLE
20.04 timeline?

### ISSUE THREAD

**Issue by arlofaria** [phusion/baseimage-docker#554]
Just curious: is there a timeline for baseimage-docker to support the 20.04 LTS release of Ubuntu?

Has this already been announced/discussed elsewhere?

Also, just wanted to say thanks: I'm a big fan of this project and appreciate that it's generally worked quite well -- and thus doesn't require much activity or maintenance on this repo.

**Comment by Theaxiom** [comment]
@arlofaria If you feel up to it, you can certainly try it and see what breaks, push up your branch and create a PR, etc. We can go from there.

**Comment by samip5** [comment]
@Theaxiom I did the PR, but it seems like Travis is not allowed to access encrypted ENV variables so it cannot build.

**Comment by PikachuEXE** [comment]
Maybe we should fix master build first?

**Comment by samip5** [comment]
> Maybe we should fix master build first?

There's really nothing we can fix.
https://travis-ci.org/github/phusion/baseimage-docker/jobs/677489186
![image](https://user-images.githubusercontent.com/1703002/81057390-fbfb9000-8ed4-11ea-8d32-b8ddba25e260.png)

**Comment by samip5** [comment]
@Theaxiom You are aware that the build is failing, all the PR's cannot be built?

**Comment by Theaxiom** [comment]
I'll test locally and then merge it.

**Comment by samip5** [comment]
I rebased my PR, so it only has the base image change now, as needed.

**Comment by Theaxiom** [comment]
Thank you.

**Comment by Theaxiom** [comment]
Should probably release a new version first from master before merging this
in, too. I will do that.

**Comment by Theaxiom** [comment]
I haven't forgot, just been very busy at work. I am doing this tonight, thanks for all your hard work and contributions!

**Comment by Theaxiom** [comment]
Yeah I know, I said I would do this last night... didn't quite make it. I have it at the top of my priority list.

**Comment by Theaxiom** [comment]
It appears that I have been removed from the phusion organization on Docker Hub. Currently looking into this.

**Comment by Theaxiom** [comment]
Apparently the organization changed on Docker Hub and I have to be re-added, @FooBarWidget sent an email back in February about it. Sit tight and we will get this resolved. :)

**Comment by Theaxiom** [comment]
Sandro,

I completely agree with you and I am a DevOps architect, I build CI(CD
pipelines for a living. Right now I am too busy and overloaded both
personally and professionally to fix the CI/CD pipeline, I am actually
deferring work at this very moment to get this release out to the community
because I honor my commitments. Since you seem so knowledgeable about the
subject, I would suggest you fix the CI/CD pipeline and push the changes in
a pull request and I will review them and merge them in. Thanks!

Thanks,
Travis Rowland
http://travisrowland.com
http://linkedin.com/in/travisrowland
http://about.me/travisrowland

-----------------------------------------------

This e-mail is privileged and confidential.  Do not forward, copy or print
without authorization.  If you are not the intended recipient of this
E-mail, you are hereby notified that any dissemination, distribution or
copying of this message is strictly prohibited. If misdirected, please
delete and notify the sender by e-mail at travis.rowland@gmail.com.

CAUTION: E-mail sent through the internet is not secure and could be
intercepted by a third party. For your protection, avoid sending
identifying information, such as account numbers or social security numbers.

**Comment by SuperSandro2000** [comment]
I would love to help but the fails are [related to a permission issue](https://travis-ci.org/github/phusion/baseimage-docker/jobs/692704080#L1189) on Docker HUB and I am afraid that I can't help there.

This already got [mentioned a few comments up](https://github.com/phusion/baseimage-docker/issues/554#issuecomment-623977873).

**Comment by danryu** [comment]
As already mentioned, the only apparent problem with the CI/CD build are missing credentials for the "docker push" - as at https://travis-ci.org/github/phusion/baseimage-docker/jobs/692704078#L1185

Hopefully sorting out new valid credentials for Phusion on DockerHub won't be too difficult?

Would be good to get a 20.04-based phusion baseimage sorted as I would love to test using some software (particularly Wine v5) that is awkward to shoehorn into 18.04.

Cheers!

**Comment by Theaxiom** [comment]
I got my credentials restored for phusion, pushing `phusion/baseimage-docker:bionic-1.0.0 now`

**Comment by Theaxiom** [comment]
I created https://github.com/phusion/baseimage-docker/releases/tag/focal-1.0.0-alpha1 and it will automatically build a pre-release and push to Docker Hub.

**Comment by Theaxiom** [comment]
Ugh, just remembered that you can't have more than 1 hyphen in a Docker image tag. I will fix it by pushing another tag `focal-1.0.0alpha1`

**Comment by Theaxiom** [comment]
Here you go: https://github.com/phusion/baseimage-docker/releases/tag/focal-1.0.0alpha1

**Comment by samip5** [comment]
@Theaxiom Could you fix the build error? https://travis-ci.org/github/phusion/baseimage-docker/jobs/694582397#L1806

**Comment by Theaxiom** [comment]
@samip5 it started failing when the base image was switched to `focal` -- I will look into it when I have time, unless someone else can get to it before me.

**Comment by Theaxiom** [comment]
`warning: /etc/service/sshd: unable to open supervise/ok: file does not exist`

**Comment by samip5** [comment]
But I don't understand why it's complaining it like that?
