### ISSUE TITLE
How to expose SSH publicly via node port

### ISSUE THREAD

**Issue by dsargent3220** [phusion/baseimage-docker#559]
The instructions say
"baseimage-docker does not expose the SSH server to the public Internet by default."
But they do not say how to turn this functionality on.
Is there a simple method to enable exposing this via a node port so I can ssh into a pod from a machine outside the cluster?
I've tried and cannot get it to work.  SSH just hangs.

**Comment by Theaxiom** [comment]
@dsargent3220 may you please provide some more information about what you have tried? Also it would be helpful if you provided output from your commands, etc.

**Comment by kingdonb** [comment]
The instructions are not for Kubernetes, they are written for Docker machines. Kubernetes has some additional barrier to entry, I am assuming you had trouble climbing over it for one reason or another (it's ok!) If you're creating a service to expose SSH via nodeport, three or more things could have gone wrong, attaching this list in case you haven't figured it out, or for the next guy:

1) your NodePort service's exposed port is firewalled. (This can happen by default on some k8s providers, since nodeport is in a range around 30000-32767, those are unusual ports for services like SSH or HTTP, usually you only want those exposed to load balancers, who can remap them to the expected port for external consumer. Assuming you don't want a load balancer, then...)

2) you expected a different port than NodePort opened (again, the port will be in the range 30000-32767, so make sure you're accessing the service on the right port)

3) your Service isn't actually reaching the running pod behind it (you can test this from within the cluster! if the service is called "myssh" in the namespace "default" you should be able to use an ssh client to connect to it with `ssh myssh.default.svc`

It might be good to provide instructions on how to run this image in Kubernetes, this is something I've worked on myself recently, in the past few months anyway. If you'd like to open a separate issue about that, please feel free to "at" me! I might get around to it on my own, but it is more likely to get done if someone will pair with me and hold me accountable.
